import sys
import re
import json
import time
from openai import OpenAI
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage

DEVELOPER_SYSTEM_PROMPT = """You are the specialized Developer agent in a multi-agent swarm.
Your job is to take the plan generated by the Architect and execute the coding tasks.
You are an expert programmer. Write high-quality, clean code.

Rules:
1. Focus ONLY on the coding tasks assigned to you.
2. Output tool calls to edit files (`write_file`, `patch_file`) or run commands.
3. Use the following format for tool calls: <tool_call>name{{"arg": "val"}}</tool_call>
4. If the plan is purely informational (e.g., answering a question) or does not require modifying files or running commands, DO NOT output any tool calls. Just state that no action is needed.
5. Do not explain your actions unless necessary. Let the code speak.
"""

def execute_develop(state, client, workspace_path):
    """
    Calls the LLM to execute coding tasks based on the plan.
    """
    # Load available tools
    allowed = ["read_file", "write_file", "patch_file", "run_terminal", "browser_navigate", "browser_click", "browser_type", "browser_screenshot"]
    tool_help = "\n".join([f"- {t}" for t in allowed])

    # Get the plan from the state (we assume the Architect stored it in the state)
    plan = state.get("plan", "No plan provided.")
    
    sys_prompt = DEVELOPER_SYSTEM_PROMPT + f"\n\nCURRENT PLAN TO EXECUTE:\n{plan}\n\nAvailable Tools:\n{tool_help}"

    messages = [
        {"role": "system", "content": sys_prompt},
        # We can also pass the history or just the relevant context to keep it clean
        {"role": "user", "content": f"Please execute the next step of the plan. Workspace: {workspace_path}"}
    ]

    start_time = time.time()
    
    print("Developer Agent: Calling LLM...")
    try:
        from core.llm import call_llm
        response = call_llm(
            client=client,
            messages=messages,
            model_name=state.get("model_name", "gemma-4-e4b"),
            temperature=0.2,
            max_tokens=4096
        )
        output = response.choices[0].message.content
        
        from rich.console import Console
        c = Console()
        c.print("[bold blue]Developer Agent is coding...[/bold blue]")
        c.print(f"[dim]{output}[/dim]")
        
        elapsed_ms = int((time.time() - start_time) * 1000)
        
        return {
            "internal_monologue": output,
            "messages": [AIMessage(content=output)],
            "token_usage": {
                "prompt": 0,
                "completion": 0,
                "time_ms": elapsed_ms
            }
        }
    except Exception as e:
        return {"error": f"Developer Agent failed: {str(e)}"}
